# Generated by Django 3.1 on 2021-02-10 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('ano', models.IntegerField()),
                ('studio', models.CharField(max_length=128)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField()),
                ('valor_total', models.FloatField()),
                ('fitas', models.ManyToManyField(to='Locadora.Fita')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fita',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitas', to='Locadora.titulo'),
        ),
    ]
